[package]
name = "hello_embedded_rust"
version = "0.1.0"
authors = ["Mikael Wikström <leakim.wikstrom@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[features]
default = ["std"]
std = []

[lib]
name = "work"
crate-type = ["staticlib"] # Creates static lib

